project_id = "vmgrnkuhprxowcvydnvm"

[functions.create-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.create-demo-users]
verify_jwt = false

[functions.send-email]
verify_jwt = false
